### ISSUE TITLE
Make roads with slow speed < 40 km/h more visible

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#101]
Is it possible to add some sort of marking for roads with no cycle infrastructure that has tagging of lower than 40 km/h? For example similar to "Markastier"/dotted line, but yellow?

For legend / Tegnforklaring: "Lavhastighetsgater".

**Comment by leonardehrenfried** [comment]
I think this is possible. @Beck-berry has assigned herself, so please take a look at it.

**Comment by Beck-berry** [comment]
I created the conditions as:
* `maxspeed` is in km/h and less than 40
* there's no `bicycle=no` tag or `motorroad=yes` tag
* there isn't any postitve kind of `cycleway` tag (eg. `cycleway=both`)
* `highway` tag has other than "cycleway" value

Examples in Drammen:
* [Hauges gate ](https://www.openstreetmap.org/way/1240814153) (maxspeed=40) 
* [Andreas Thunes gate](https://www.openstreetmap.org/way/24507465) (maxspeed=30)

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/f4d73210-4de3-41b1-9e29-a47228e4d7bf)

**Comment by tsobuskerudbyen** [comment]
Looks good. Can we try with all `maxspeeds` lower than 40 km/h. So, please exclude 40 km/h. 

Also, please make sure to include:
1. `highway=living_street`. Like: https://www.openstreetmap.org/way/115379007 and
2. `highway=pedestrian` and no `bicycle=no`. Like: https://www.openstreetmap.org/way/40619440

**Comment by Beck-berry** [comment]
`highway=pedestrian` roads already have a dashed line notation in a similar colour and so, that would look really weird if used together. For example [Nedre Torggate](https://www.openstreetmap.org/way/454613820#map=20/59.74365/10.20694&layers=C)
* Without "slow road" notation: 
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/138cb8de-db9d-48c0-85f4-6b7b32e94dc3)
* Together:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/2eaf2256-e21d-4325-9402-1439f2f8c0cf)


Is it ok for you? Should we use the "slow road" notation with another colour?
Since "slow roads" will be switchable, we have to consider the display with and also without it.

**Comment by Beck-berry** [comment]
@tsobuskerudbyen Could you help me make a dicision on this?

**Comment by tsobuskerudbyen** [comment]
Sorry here as well. `highway=pedestrian` without the "slow road" dashed line notation, please. Thanks.
