### ISSUE TITLE
Make a sub service of Cycling Norway into a Slippy Map/Widget 

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#27]
Similar issue #11, but not the same.

Have the Cycling Norway solution also work as a [Slippy Map](https://wiki.openstreetmap.org/wiki/Deploying_your_own_Slippy_Map)/Widget - Similar to https://tiles.stadtnavi.eu/widget/. 

The idea here is to make a map tool that at least for all *.[kommune.no](http://kommune.no/) (and [buskerudbyen.no](http://buskerudbyen.no/) [kolumbus.no](http://kolumbus.no/), [brakar.no](http://brakar.no/), banenor.no, etc.) domains are free to use. And that promotes the use of walking, cycling and public transport. And not private car usage like a lot of maps do today. (Side note: Unsure about the need to limit usage and load on servers here.)

So, it is easy to show a location - with a pin - and how to get from any starting point to the pinned location from the embedded map. For example, one button to get info on travel with public transport (using Entur's tools here) or going by bike (using Cycling Norway tools) – and maybe even with a combination of private bike and public transport (utilizing Sykkelhotell and other bicycle parking). The map should be visually appealing and have the possibility to show:
1) A pin for the location in question, with – hopefully – some additional information on the closest public transportation stop(s).
2) Some standard buttons to make it full size, zoom, etc. (Similar to uMap, and perfect if some of the design aspects could be customizable here.)
3) A button to open to and from search for cycling where the destination is already filled in. How to handle size of the map, compared to be able to show details of the route.
4) A button with Entur services. In the most basic configuration a from field to search, and when this is added a new tab in the browser opens with [standard(?) Entur search like this](https://entur.no/reiseresultater?transportModes=rail%2Ctram%2Cbus%2Ccoach%2Cwater%2Ccar_ferry%2Cmetro%2Cflytog%2Cflybuss&date=1679059038993&tripMode=oneway&walkSpeed=1.4&minimumTransferTime=120&timepickerMode=departAfter&startId=KVE%3ATopographicPlace%3A3005-Glassbl%C3%A5serveien&startLabel=Glassbl%C3%A5serveien&startLat=59.71934755553268&startLon=10.26072049905552&stopId=133185992&stopLabel=Daleg%C3%A5rdsveien%2074&stopLat=59.761859239950965&stopLon=10.125492793159967 
). The to-field is hidden or automatically populated with the address of the place we want to travel to. 

**Goal**: To replace things like this:

**Scenario 1: Maps to a specific location**
https://www.drammen.kommune.no/tjenester/barnehage/barnehagene-i-drammen/aronslokka-barnehage/ and https://www.banenor.no/reise-og-trafikk/stasjoner/-H-/Holmestrand/
And have a service that is easy to use and embed location for libraries, public swimming pools, beaches, schools, etc.

See GUI mockup number one under.

**Scenario 2: Maps that show road works for cyclists and pedestrians**
As an alternative to making images and manual work for informing travelers.
1. Step one is to make OSM data visible in the Cycling Norway solution, by using e.g. the `construction=cycleway` tag. This has to be done at least 24 hours before the change in order to be visible in the solution (and Entur).
1. In this way any route OTP will also not route over the work. 
1. Additional steps is to make a dedicated web UI for just these kinds of changes. This makes it then easier to change status, and no need for OSM Id or JOSM knowledge is needed.
1. For this over it is also possible to automatically revert the changes as well, so only one registration is needed. If the known date when the work is finished. 
To make something to replace this: https://www.stavanger.kommune.no/vei-og-trafikk/stavanger-pa-sykkel/endringer-i-sykkelruter/

See GUI mockup number two under.

**Scenario 3: Promote new cycle infrastructure and solutions**
Supported today. As long as the solution is added to OSM at least 24 hours before.

**Comment by tsobuskerudbyen** [comment]
Mocup GUI for this URL: https://drammensbadet.no/om-badet/hvor-er-vi/
![bilde](https://github.com/buskerudbyen/cycling-norway/assets/70061303/fdbafcde-bd7b-4728-b0c8-e5e3f413c2ba)

**Comment by tsobuskerudbyen** [comment]
Mockup GUI for: https://www.stavanger.kommune.no/vei-og-trafikk/stavanger-pa-sykkel/endringer-i-sykkelruter/
![bilde](https://github.com/buskerudbyen/cycling-norway/assets/70061303/8ee4c23c-d472-4a07-9e2c-fd525b20f3d7)

**Comment by tsobuskerudbyen** [comment]
Documentation should be updated here: https://docs.google.com/document/d/1hLwQOiYDp_cYGWgkrOZIB0tnzq_Fk_NYxnCWIBCwJRI/edit?usp=sharing

**Comment by michaeljohansen** [comment]
> @michaeljohansen: You also mentioned some security issues with iframe, please eloborate on this as well.

Not a concern. I've already talked to Leonard and we will make the widget as a script to be included (not using an iframe). 😊 Besides, potential security issues with iframes are more of a concern when using someone else's code in an iframe in our product rather than when other people use our code in an iframe in their product. At least for us. 😅

**Comment by michaeljohansen** [comment]
Short status update: I'm confident I'll get this ticket done before the time is up, while also improving the code of the project to make it more maintainable for the future! 😊 

Long status update:
1. Spent the first two days reading all the commits to get to know the codebase
2. Spent a day [fixing runtime errors](https://github.com/buskerudbyen/cycling-norway/pull/113) to make the project run cleanly
3. Decided on a strategy for the widget: Will have the widget code in this repository to avoid ending up with two different projects, and to re-use code where possible. Decided to publish as a bundled script that users can include and use directly (instead of publishing an NPM package or making the widget available as an iframe).
4. Tried to make the base for the widget in a separate folder with Webpack and it's own `package.json` and tooling. The toolchain got a bit out of hand for something that didn't seem to large, so I decided to start over using the more modern Bun.
5. Started making the base of the widget (still in a separate folder `/widget/`), but now using [Bun](https://bun.sh/). Got further than with Webpack with far less effort. Did however meet a roadblock with a bundling issue that is not resolved yet, spent half a day trying to find the solution to that.
6. While trying to find the solution for the Bun bundling issue I did pair programming sessions with @Beck-berry, which has resulted in the entire project being upgraded quite a bit code-wise: We now have [React hooks and all the code has been formatted](https://github.com/buskerudbyen/cycling-norway/pull/115) 🎉 and all the code has been [rewritten to TypeScript](https://github.com/buskerudbyen/cycling-norway/pull/119) together with @Beck-berry 🎉 !
