### ISSUE TITLE
New snow ploughing status colour: White for "It is snowing" – Highest priority

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#35]
Klaus: 
>We updated the API a bit to include a Feature in the extraction that gives some weather features to you and the point where it’s calculated for. This feature will normally be in the end of the feature list for the geojson.
> 
> Sadly we have not yet received any data, but I suspect as soon as they are done with the Drammen ski thing you will see data come.
> 
> The added record looks like this (the one in bold [Trond: Did not get bold in copied text. It is all code in line after "features"]):

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          10.145973,
          59.718913
        ]
      },
      "properties": {
        "from_rsu": 6450416887791616,
        "weather_status": "cloudy",
        "precipitation_mmh": "0.0",
        "air_temperature": "-4.4"
      }
    }
  ]
}
```

> The weather type is mapped to these type codes: https://api.met.no/weatherapi/weathericon/2.0/documentation

Trond: 
> Gunn just made me aware of that Applied Autonomy has added information on weather conditions. Can you please look into the possibility to add the third status information/colour - white = it is snowing, and cyclists cannot know what type of condition they can expect. "Data in from_rsu: <id>_status, preciptiation"

Leonard: 
> Can we talk a little more about the visualisation? For example, should the white line be overlaid the orange/green ones?

Trond today: The priority must be:
1. White – It is snowing.
2. Green – Some snow ploughing has been done.
3. Orange – It is not snowing, and the snow has probably been cleared, but it may be slippery and conditions in general are unclear. 

For legend Tegnforklaring: White line – "Det snør. Brøyting pågår. Det prioriteres etter kontrakt med veieier".

### Acceptance criteria

- [x] In the backend, check the contents of the GeoJSON file for the weather data. 
- [x] If it snows AND the last snow plow was more then 3 hours ago, then insert a special line into the Geojson which indicates that it's snowing.
- [x] In the frontend, add code to display the special white line.

**Comment by leonardehrenfried** [comment]
So the white line should only be shown if the data says so AND the last plowing was more than 3 hours ago, correct?

**Comment by tsobuskerudbyen** [comment]
Yes, this is correct.

**Comment by leonardehrenfried** [comment]
@Beck-berry @tsobuskerudbyen I've deployed the backend for this. Next up is the visualisation in the frontend.

**Comment by Beck-berry** [comment]
I tried to simulate a snowy road and it looks like this:

![image](https://user-images.githubusercontent.com/46535522/234339297-f926d3d8-d814-4e6d-aff6-a25a7533d0e8.png)

![image](https://user-images.githubusercontent.com/46535522/234341681-ab76654c-2240-47c6-b5c1-fc7fc7bf6994.png)

@tsobuskerudbyen Two questions:
- I would suggest that the text for the legend could be shorter. For the popup info, we can keep the longer text, for sure. 
- What solution would you prefer for the white lines to be visible at the legend and in the popup? Since the background is white both places, we should change the line colour (slightly different white) or the background (for all the floating modules or only for the icons). I'm not much of a designer and I could only think of these solutions, but any good suggestions are welcomed!

**Comment by tsobuskerudbyen** [comment]
1. Yes, agree that the text is way too long in the legend. Please shorten it down to: "Det snør. Brøyting pågår."
2. I would try a background colour for the box (I guess it is a square icon/image). Go for the green colour that is natural=wood as the colour. Can it be done on all three snow info lines then?
![bilde](https://user-images.githubusercontent.com/70061303/234524130-c54a6e1f-8e7f-4818-ad2a-8506a53ca5de.png)

**Comment by leonardehrenfried** [comment]
I also believe a border around the snow lines would be a good idea.

@Beck-berry I'm not sure if you can style GeoJSON with a border but if you can't you can draw a slightly wider line behind with a darker colour.

**Comment by Beck-berry** [comment]
Does this look better?
Unfortunately, I cannot add a border to a line ([see documentation](https://maplibre.org/maplibre-style-spec/layers/#line)), so it had to be another layer. I'll go on with the the bordering of the little icons at the legend and in the popup, since they have to be manipulated one by one.

![Image](https://user-images.githubusercontent.com/46535522/235363739-4fe6bd6f-379f-4a25-aa47-b2aaa5435a51.png)

**Comment by tsobuskerudbyen** [comment]
All of them over look much better than what we currently have. What was the choice here?

**Comment by Beck-berry** [comment]
If you do not have a preference, I'd go with a background for the icon in the popup and the legend, and keep the black border for the map line.
