### ISSUE TITLE
Solve UX on smaller screens (mobile devices)

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#8]
Showing the cycling Norway web page on a small screen will result in overlapping user interface components. See screenshot. Can this be rectified by moving things around? For example, having "Tegnforklaring" window either minimized by default or moving it down and hide it while you are typing? I do not know what is possible in the solution here, so I'm open for suggestions here.
![bilde](https://user-images.githubusercontent.com/70061303/220554739-3c9967b8-a41c-4ed7-a2bd-6eb95007f6ce.png)

**Comment by Beck-berry** [comment]
I came up with a part-time solution for mobile devices. For screens with the width > 430px, it looks better only by rerendering and resizing the elements. (See #13 ) 
Next step probably would be to minimize the legend. I think by moving it lower it would cover unpleasantly big part of the map. We could create two top buttons: one would show the search fields and one would show the legend. When any of them is open, the other is closed. What do you think?

**Comment by tsobuskerudbyen** [comment]
Good suggestions. Try it out.

**Comment by Beck-berry** [comment]
I moved the menu upper on all screen sizes as it seemed more comfortable for me. Let me know if you think otherwise.

![Képernyőkép_2023-03-12_20-53-15](https://user-images.githubusercontent.com/46535522/224569749-cba1930c-75bd-4dc8-9fd3-9f468764708f.png)

The legend control panel we use ([MaplibreLegendControl](https://github.com/watergis/maplibre-gl-legend)) offers a "closed" state, when only an icon is showed and used as a button to open the details. We can put any SVG there.
For the search fields I introduced a new button ("Toggle search" for now) which is only visible on screens < 500px, and toggles both search fields.
For now both the legend and search can be opened at the same time. (Work in progress regarding this.)

@tsobuskerudbyen  What do you think so far?

![Képernyőkép_2023-03-12_20-51-09](https://user-images.githubusercontent.com/46535522/224569817-89fc9860-7e4e-4b89-9eaf-fc21cad7a6f2.png)
![Képernyőkép_2023-03-12_20-51-23](https://user-images.githubusercontent.com/46535522/224569820-c4bc6222-99cd-4e3b-acd5-7c099fda3126.png)
![Képernyőkép_2023-03-12_20-52-06](https://user-images.githubusercontent.com/46535522/224569821-624bf2f2-9385-4933-999b-88ae47961c91.png)


(Screenshots are made on a 375px wide screen.)

**Comment by leonardehrenfried** [comment]
I think this is quite good. Lets have it!

**Comment by tsobuskerudbyen** [comment]
Looks good. Disregard bullet no. 2 in #21 then. Thanks!

**Comment by Beck-berry** [comment]
Can I ask for a better text on the toggle button? We could also use an icon if you prefer.

**Comment by tsobuskerudbyen** [comment]
Yes, well spotted! Please use: "Tekstsøk".
