### ISSUE TITLE
More cycle route Information visible in the map

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#97]
Is it possible to add some more basic cycle route information details? On click? But, when more than one route on a road what then?

1. Start with the description tag.
2. Change the language if there are other present. Possible?
3. Pictures? Is it possible? Where and how?

Example: https://www.openstreetmap.org/relation/11921767

**Comment by tsobuskerudbyen** [comment]
@leonardehrenfried: Can you please comment on this one?

**Comment by tsobuskerudbyen** [comment]
Great. Can some initial work be done here then? Look into how it is displayed for example.

**Comment by leonardehrenfried** [comment]
@Beck-berry can take this on

**Comment by Beck-berry** [comment]
I created a demo. Right now the popup opens on the click on the name of the route, since it's visible. The popup displays the `name`, the `from` - `to` and the `description` tags.

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/f0afd127-00e5-4630-a4fc-392cd32e3045)

Sadly, the other routes in Drammen do not have any information other than the names. Question is, do you want to display any popup if there is no description for the relation?
What languages should we display? Sølvveien has German `name` and `description` and English `name`, thus the content would differ per language.

I have an idea for multiple routes: on the click on the road, a selector panel should appear in the popup. Eg. three rows for "Sølvveien", "Åssiden" and "Bragernes torg - Vinnes" relations where they have a common part (eg. Ovre Torggate). The user then can select one and if the route has some detailed data, it would appear as above; otherwise we could display a common text with the OSM URL to encourage the user to add a description(?) or any other common text you'd like.
@tsobuskerudbyen What do you think?

**Comment by tsobuskerudbyen** [comment]
Sorry. Overlooked this one. Looks good, and I like your suggestion. But, what if you want a destination or start location close to the route. Will it be confusing, or even cause irritation, that the route information pops up?

**Comment by Beck-berry** [comment]
That should be really close 😄 And if so, this problem would occur with any other popup. Do you know about that, is it irritating? (I don't know how and how many reactions / bug reports / comments you get.)

**Comment by tsobuskerudbyen** [comment]
Cool. :) No feedback from users so far (it is a bit hard to find the e-mail perhaps), and only some feedback from people I cooperate with. Other than questions for functionality. This ticket is an example from Vestfold County and a cycle route to [the End of the World](https://www.visitvestfold.com/verdensende/) (!). Another example is the colour one (#109). From Gjøvik municipality.

**Comment by Beck-berry** [comment]
When multiple routes found:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/5f9b2b43-e2be-4da3-9a5c-369f26b97869)

When there are no description / from / to information:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/93cdd7fc-db5f-46d4-b6c8-08d8e4d1b275)

@tsobuskerudbyen How do you like it? Any ideas are welcome!

I recommend deploying it without the language change at first, maybe you'll get more feedback on it! :) (Eg. what languages should we display; what to display when there are not enough information in OSM.)

**Comment by tsobuskerudbyen** [comment]
Looks good. Is it possible to prioritize the order and the routes visible - or even enabled - in selection box UI? So, if no further description is available, they can be put on the bottom and greyed out (so not possible to click on it) and then, in your example, it is only "Sølvveien" that is on top and enabled. 

Norwegian translation: "Flere sykkelruter funnet. Vennligst velg:". If too long. Try: "Velg én av flere sykkelruter:" 

**Move out to a new ticket if needed** 

**1] Type of route** 
Also, in the selection box, please add:  
- If `network=icn` = `name` + " (internasjonal)" 
- If `network=ncn` = `name` + " (nasjonal)" 
- If `network=rcn` = `name` + " (regional)" 
- If `network=lcn` = `name` + " (lokal)" 

  

**2] Website link** 
Can we add to the main information window:  
- if `website` is present. Shown: "[Webside med mer informasjon](https://storymaps.arcgis.com/stories/18556e7f601a4b76915f132d94ae1a6a)" 

Example of a good one: https://www.openstreetmap.org/relation/1213626

**Comment by Beck-berry** [comment]
@tsobuskerudbyen What do you think?

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/50d7592e-9c9d-4dc1-a184-20f4fc411c35)

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/ffe8ed55-d8ae-41b5-b978-d00008f53e32)

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/fc866078-e5a5-4cd1-9ef2-e9db3f301206)

**Comment by tsobuskerudbyen** [comment]
Look perfect. Good work!
